name: qr_code_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
