// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQfQghUzQwBL9Gds2D8Jfywbwh-sGiMeo',
    appId: '1:155133167876:web:9a3a6ead1d9ffb13f4a851',
    messagingSenderId: '155133167876',
    projectId: 'qrcode-b549b',
    authDomain: 'qrcode-b549b.firebaseapp.com',
    storageBucket: 'qrcode-b549b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjAJLNw_IuCbCXHT0Bw2vkWAD2-3wSpRM',
    appId: '1:155133167876:android:e513035d845e29c2f4a851',
    messagingSenderId: '155133167876',
    projectId: 'qrcode-b549b',
    storageBucket: 'qrcode-b549b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmDekJJRBCCW_EGmN_r0ymVdRqI93EQ40',
    appId: '1:155133167876:ios:c60a4c6d4dcb4d1cf4a851',
    messagingSenderId: '155133167876',
    projectId: 'qrcode-b549b',
    storageBucket: 'qrcode-b549b.appspot.com',
    iosClientId: '155133167876-rkds2udocr2ikr2cm7dnnvau6l7hcto4.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCodeGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmDekJJRBCCW_EGmN_r0ymVdRqI93EQ40',
    appId: '1:155133167876:ios:c60a4c6d4dcb4d1cf4a851',
    messagingSenderId: '155133167876',
    projectId: 'qrcode-b549b',
    storageBucket: 'qrcode-b549b.appspot.com',
    iosClientId: '155133167876-rkds2udocr2ikr2cm7dnnvau6l7hcto4.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCodeGetx',
  );
}
